site_name:          Term 3 Notes
site_url:           https://notes.com
docs_dir:           docs/
repo_name:          ""
repo_url:           ""
use_directory_urls: true

nav:
  - About:                          "index.md"
  - DDW:
    - Notes: "ddw/notes.md"
    - Deadlines: "ddw/deadlines.md"
    - Info: "ddw/to_know.md"
  - Phy:
    - Notes: "phy/notes.md"
    - Deadlines: "phy/deadlines.md"
    - Info: "phy/to_know.md"
    - PSET1: "phy/pset1.md"
    - PSET2: "phy/pset2.md"
    - PSET3: "phy/pset3.md"
    - PSET4: "phy/pset4.md"
  - Maths:
    - Notes: "maths/notes.md"
    - Deadlines: "maths/deadlines.md"
    - Info: "maths/to_know.md"
  - HASS:
    - Notes: "hass/notes.md"
    - Deadlines: "hass/deadlines.md"
    - Info: "hass/to_know.md"

markdown_extensions:
  - admonition                # Create not and warning boxes        https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - pymdownx.caret            # Handling sub- and superscripts      https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.mark             # Highlighting of text                https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.tilde            # Strikethrough of text               https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.keys             # Add styling keyboard keys           https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.tabbed           # Tabs                                https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.details          # Collapsable elements                https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.highlight:       # Highlighting code blocks            https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
      linenums: true
  - pymdownx.emoji:           # Emojis                              https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite     # Inline code highlighting            https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
  - pymdownx.superfences      # Complicated code fences             https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.smartsymbols     # Creating special characters         https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.arithmatex:      # Preserve LaTeX math equations       https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
      generic: true
  - pymdownx.tasklist:        # Creating Check-able tasklist        https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      separator: '[\s\-\.\_]+'

extra_css:
  - style.css

theme:
  name: material
  language: en
  favicon: imgs/code.svg
  icon:
    logo: octicons/file-code-24
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    # - navigation.sections
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Times New Roman
    code: Source Code Pro
